def make_report(title, notes):

    report = f"""
========================================
{title}
AI Research Paper Tutor Notes
========================================

{notes}

========================================
Generated by Paper Tutor AI
========================================
"""

    return report
